"use client";

// Renders the five Etsy listing-image previews for a recipe as CSS cards
// (hero, ingredients, scent pyramid, what's included, lifestyle) — a faithful
// preview render of what fragbot/imagesgen produces as 2000×2000 JPEGs, drawn
// client-side so the dashboard needs no binary assets. Labeled as a preview.

import type { Recipe } from "@/lib/types";
import { slugHue } from "@/lib/format";

function hueStyle(slug: string): React.CSSProperties {
  const h = slugHue(slug);
  return {
    background: `linear-gradient(150deg, hsl(${h} 38% 22%), hsl(${(h + 40) % 360} 42% 12%))`,
  };
}

function CardShell({
  index,
  label,
  slug,
  children,
  badge,
}: {
  index: number;
  label: string;
  slug: string;
  children: React.ReactNode;
  badge?: string;
}) {
  return (
    <figure className="prev-card">
      <div className="prev-canvas" style={hueStyle(slug)}>
        {children}
        {badge ? <span className="prev-badge">{badge}</span> : null}
      </div>
      <figcaption className="prev-caption">
        <span className="prev-index">{index}</span> {label}
      </figcaption>
    </figure>
  );
}

export default function PreviewStrip({ recipe }: { recipe: Recipe }) {
  const { slug, recipe_name, category, theme, price_usd, yield_text, ingredients } = recipe;
  const top = recipe.scent_profile.top_notes.slice(0, 3);
  const heart = recipe.scent_profile.heart_notes.slice(0, 3);
  const base = recipe.scent_profile.base_notes.slice(0, 3);

  return (
    <div className="prev-strip" title="Preview renders — mirror the 5 listing images the pipeline generates">
      <CardShell index={1} label="Hero card" slug={slug} badge="Preview render">
        <div className="prev-hero">
          <div className="prev-cat">{category} recipe</div>
          <div className="prev-name">{recipe_name}</div>
          <div className="prev-sub">DIY digital download · {theme}</div>
        </div>
      </CardShell>
      <CardShell index={2} label="Ingredients" slug={slug}>
        <div className="prev-block-label">Ingredients</div>
        <ul className="prev-list">
          {ingredients.slice(0, 4).map((i) => (
            <li key={i.name}>
              <span>{i.name}</span>
              <em>{i.amount}</em>
            </li>
          ))}
        </ul>
      </CardShell>
      <CardShell index={3} label="Scent pyramid" slug={slug}>
        <div className="prev-pyramid">
          <div className="py-row py-top">
            <b>Top</b>
            <span>{top.join(" · ")}</span>
          </div>
          <div className="py-row py-heart">
            <b>Heart</b>
            <span>{heart.join(" · ")}</span>
          </div>
          <div className="py-row py-base">
            <b>Base</b>
            <span>{base.join(" · ")}</span>
          </div>
        </div>
      </CardShell>
      <CardShell index={4} label="What's included" slug={slug}>
        <div className="prev-block-label">What&apos;s included</div>
        <ul className="prev-list prev-plain">
          <li>📄 5-page printable recipe card (PDF)</li>
          <li>{yield_text}</li>
          <li>Step-by-step instructions + safety notes</li>
          <li>Ingredient amounts &amp; purpose list</li>
        </ul>
      </CardShell>
      <CardShell index={5} label="Lifestyle" slug={slug} badge={`$${price_usd.toFixed(2)}`}>
        <div className="prev-block-label">{theme}</div>
        <p className="prev-life">Handmade scent, ready in minutes — a {category} for every
          day. Download once, craft forever.</p>
      </CardShell>
      <div className="prev-note">Image area · client-side preview render of the 5 listing images (2000×2000 px JPEGs are generated by the pipeline).</div>
    </div>
  );
}